# Generated by Django 6.0.3 on 2026-03-10 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scryfall_id', models.UUIDField(unique=True)),
                ('oracle_id', models.UUIDField()),
                ('name', models.CharField(max_length=200)),
                ('set_code', models.CharField(max_length=10)),
                ('collector_number', models.CharField(max_length=20)),
                ('image_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_public', models.BooleanField(default=True)),
                ('card_count', models.PositiveSmallIntegerField(default=0)),
                ('avg_cmc', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('commander', models.ForeignKey(help_text='First commander', on_delete=django.db.models.deletion.PROTECT, related_name='commander', to='blog.card')),
                ('partner_commander', models.ForeignKey(blank=True, help_text='Second commander if both have partner', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commander_partner', to='blog.card')),
            ],
            options={
                'verbose_name': 'Deck',
                'verbose_name_plural': 'Decks',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DeckCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('is_commander', models.BooleanField(default=False)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.card')),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.deck')),
            ],
        ),
        migrations.AddConstraint(
            model_name='deck',
            constraint=models.UniqueConstraint(fields=('author', 'name'), name='unique_deck_name_per_user'),
        ),
        migrations.AlterUniqueTogether(
            name='deckcard',
            unique_together={('deck', 'card')},
        ),
    ]
