# Generated by Django 6.0.3 on 2026-04-13 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='image_large_url',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='card',
            name='type_line',
            field=models.CharField(default='', max_length=200),
        ),
    ]
