# Generated by Django 6.0.3 on 2026-04-17 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_card_image_large_url_card_type_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='cmc',
            field=models.IntegerField(default=0),
        ),
    ]
