# Generated by Django 6.0.3 on 2026-05-18 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_card_cmc'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='color_identity',
            field=models.CharField(default='', max_length=10),
        ),
    ]
